version: '3.8'
services:
  frontend:
    container_name: frontend
    image: matowaty/train-scraper:frontend
    ports:
      - "18942:80" # Map port 80 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
      - TRAIN_SCRAPER_URL=http://train-scraper:8080 #http://host.docker.internal:8080 
      - ACCOUNT_MANAGER_URL=http://account-manager:5220 #http://host.docker.internal:5220
      - TRANSACTION_MANAGER_URL=http://transaction-manager:5221 #http://host.docker.internal:5221 
      - ANALYTICS_URL=http://analytics:5223
      - CHANGES_MANAGER_URL=http://changes-manager:5222
    networks:
      - rsww_189420_network

  train-scraper:
    container_name: train-scraper
    image: matowaty/train-scraper:scraper
    ports:
      - "18943:8080"
    networks:
      - rsww_189420_network

  account-manager:
    container_name: account-manager
    image: matowaty/train-scraper:account
    ports:
      - "18944:5220"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5220
      #LOCAL DATABASE- ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=mydb;Username=admin;Password=adminpass
      - ConnectionStrings__DefaultConnection=Host=admin-postgres_db;Port=5432;Database=RSWW_189420_DB;Username=postgres;Password=student
    networks:
      - rsww_189420_network
      - admin-postgres_default

  transaction-manager:
    container_name: transaction-manager
    image: matowaty/train-scraper:transaction
    ports:
      - "18945:5221"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5221
      - ConnectionStrings__DefaultConnection=Host=admin-postgres_db;Port=5432;Database=RSWW_189420_DB;Username=postgres;Password=student
      - CORS_ALLOWED_ORIGINS=http://localhost:18942,http://localhost:3000,http://frontend:80
    networks:
      - rsww_189420_network
      - admin-postgres_default

  analytics:
    container_name: analytics
    image: matowaty/train-scraper:analytics
    ports:
      - "18946:5223"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5223
      - ConnectionStrings__DefaultConnection=Host=admin-postgres_db;Port=5432;Database=RSWW_189420_DB;Username=postgres;Password=student
      - CORS_ALLOWED_ORIGINS=http://localhost:18942,http://localhost:3000,http://frontend:80
    networks:
      - rsww_189420_network
      - admin-postgres_default

  changes-manager:
    container_name: changes-manager
    image: matowaty/train-scraper:changes
    ports:
      - "18947:5222"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5222
      - ConnectionStrings__DefaultConnection=Host=admin-postgres_db;Port=5432;Database=RSWW_189420_DB;Username=postgres;Password=student
      - CORS_ALLOWED_ORIGINS=http://localhost:18942,http://localhost:3000,http://frontend:80
    networks:
      - rsww_189420_network
      - admin-postgres_default

networks:
  rsww_189420_network:
    driver: overlay
  admin-postgres_default:
    external: true
