"""
Analysis script for gap sequences generated by different optimization algorithms:
- Genetic Algorithm
- Cuckoo Search
- Artificial Bee Colony (ABC)
"""

import os
import re
from collections import defaultdict, Counter
import matplotlib.pyplot as plt
import numpy as np

# File paths
RESULTS_DIR = "../Results"
FILES = {
    "genetic": "BestGapsSequences2500_genetic.txt",
    "cuckoo": "BestGapsSequences2500_cuckoo.txt",
    "abc": "BestGapsSequences2500_abc.txt"
}

ALGO_NAMES = {
    "genetic": "Genetic Algorithm",
    "cuckoo": "Cuckoo Search",
    "abc": "Artificial Bee Colony"
}

COLORS = {
    "genetic": "#2ecc71",
    "cuckoo": "#3498db", 
    "abc": "#e74c3c"
}


def parse_file(filepath):
    """
    Parse a results file and extract sequence data.
    
    Returns:
        list of tuples: (population_number, sequence_list)
    """
    sequences = []
    
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            # Extract population number from label (e.g., "Child183-35" -> 183)
            match = re.match(r'[A-Za-z]+(\d+)-', line)
            if match:
                population = int(match.group(1))
            else:
                continue
            
            # Extract sequence after colon
            if ':' in line:
                seq_part = line.split(':')[1].strip()
                sequence = [int(x) for x in seq_part.split() if x.isdigit()]
                if sequence:
                    sequences.append((population, sequence))
    
    return sequences


def analyze_sequences(sequences):
    """
    Perform analysis on parsed sequences.
    
    Returns:
        dict with analysis results
    """
    if not sequences:
        return None
    
    populations = [s[0] for s in sequences]
    seqs = [s[1] for s in sequences]
    
    # 1. Number of sequences
    num_sequences = len(sequences)
    
    # 2. Average population interval between sequences
    sorted_pops = sorted(populations)
    if len(sorted_pops) > 1:
        intervals = [sorted_pops[i+1] - sorted_pops[i] for i in range(len(sorted_pops)-1)]
        avg_interval = np.mean(intervals)
    else:
        avg_interval = 0
    
    # 3. Average, Min, Max sequences (element-wise)
    # Find max sequence length
    max_len = max(len(s) for s in seqs)
    
    # Pad sequences to same length for analysis (using None for missing)
    padded_seqs = []
    for s in seqs:
        padded = s + [None] * (max_len - len(s))
        padded_seqs.append(padded)
    
    avg_seq = []
    min_seq = []
    max_seq = []
    
    for pos in range(max_len):
        values = [s[pos] for s in padded_seqs if s[pos] is not None]
        if values:
            avg_seq.append(np.mean(values))
            min_seq.append(min(values))
            max_seq.append(max(values))
    
    # 4. Most common beginnings for each length n (from end, starting from 1)
    beginning_counts = {}
    for n in range(1, max_len + 1):  # All possible lengths
        beginnings = []
        for s in seqs:
            if len(s) >= n:
                # Take last n elements (starting from 1 at the end)
                beginnings.append(tuple(s[-n:]))
        
        if beginnings:
            counter = Counter(beginnings)
            most_common = counter.most_common(10)  # Top 10 most common
            beginning_counts[n] = {
                'counts': counter,
                'most_common': most_common,
                'total': len(beginnings)
            }
    
    return {
        'num_sequences': num_sequences,
        'avg_interval': avg_interval,
        'avg_seq': avg_seq,
        'min_seq': min_seq,
        'max_seq': max_seq,
        'beginning_counts': beginning_counts,
        'populations': sorted_pops
    }


def print_analysis(algo_name, results):
    """Print analysis results for an algorithm."""
    print(f"\n{'='*60}")
    print(f"  {algo_name}")
    print(f"{'='*60}")
    
    print(f"\n1. Number of sequences generated: {results['num_sequences']}")
    
    print(f"\n2. Average populations between sequences: {results['avg_interval']:.2f}")
    
    print(f"\n3. Sequence statistics (position by position):")
    print(f"   {'Pos':<5} {'Min':<10} {'Avg':<12} {'Max':<10}")
    print(f"   {'-'*37}")
    for i in range(len(results['avg_seq'])):
        print(f"   {i+1:<5} {results['min_seq'][i]:<10} {results['avg_seq'][i]:<12.2f} {results['max_seq'][i]:<10}")
    
    print(f"\n   Min sequence: {results['min_seq']}")
    print(f"   Avg sequence: {[round(float(x), 1) for x in results['avg_seq']]}")
    print(f"   Max sequence: {results['max_seq']}")
    
    print(f"\n4. Most common sequence endings (from 1):")
    for n, data in list(results['beginning_counts'].items())[:9]:  # Show first 9 in console
        print(f"\n   Last {n} element(s) - Top 5:")
        for seq, count in data['most_common'][:5]:
            percentage = (count / data['total']) * 100
            seq_str = ', '.join(map(str, seq))
            print(f"      [{seq_str}]: {count} times ({percentage:.1f}%)")


def plot_num_sequences(all_results):
    """Plot 1: Number of sequences per algorithm."""
    fig, ax = plt.subplots(figsize=(10, 6))
    
    algos = list(all_results.keys())
    counts = [all_results[a]['num_sequences'] for a in algos]
    colors = [COLORS[a] for a in algos]
    labels = [ALGO_NAMES[a] for a in algos]
    
    bars = ax.bar(labels, counts, color=colors, edgecolor='black', linewidth=1.2)
    
    # Add value labels on bars
    for bar, count in zip(bars, counts):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                str(count), ha='center', va='bottom', fontsize=12, fontweight='bold')
    
    ax.set_ylabel('Number of Sequences', fontsize=12)
    ax.set_title('Number of Gap Sequences Generated by Each Algorithm', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(counts) * 1.15)
    
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/plot1_num_sequences.png', dpi=150)
    print(f"Saved: {OUTPUT_DIR}/plot1_num_sequences.png")


def plot_avg_interval(all_results):
    """Plot 2: Average population interval between sequences."""
    fig, ax = plt.subplots(figsize=(10, 6))
    
    algos = list(all_results.keys())
    intervals = [all_results[a]['avg_interval'] for a in algos]
    colors = [COLORS[a] for a in algos]
    labels = [ALGO_NAMES[a] for a in algos]
    
    bars = ax.bar(labels, intervals, color=colors, edgecolor='black', linewidth=1.2)
    
    # Add value labels on bars
    for bar, interval in zip(bars, intervals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{interval:.1f}', ha='center', va='bottom', fontsize=12, fontweight='bold')
    
    ax.set_ylabel('Average Population Interval', fontsize=12)
    ax.set_title('Average Populations Between Finding New Sequences', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(intervals) * 1.15)
    
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/plot2_avg_interval.png', dpi=150)
    print(f"Saved: {OUTPUT_DIR}/plot2_avg_interval.png")


def plot_common_beginnings(all_results):
    """Plot 4: Most common sequence endings (from 1) for different lengths - one plot per length."""
    
    for n in range(1, 7):  # Plot only first 6 lengths
        fig, axes = plt.subplots(1, 3, figsize=(18, 8))
        
        for idx, (algo, results) in enumerate(all_results.items()):
            ax = axes[idx]
            
            if n in results['beginning_counts']:
                data = results['beginning_counts'][n]
                if data['most_common']:
                    # Get top sequences for this algorithm
                    top_seqs = data['most_common'][:min(10, len(data['most_common']))]
                    
                    # Prepare data for horizontal bar chart
                    labels = [', '.join(map(str, seq)) for seq, _ in top_seqs]
                    percentages = [(count / data['total']) * 100 for _, count in top_seqs]
                    counts = [count for _, count in top_seqs]
                    
                    # Reverse for better display (highest at top)
                    labels = labels[::-1]
                    percentages = percentages[::-1]
                    counts = counts[::-1]
                    
                    y_pos = np.arange(len(labels))
                    
                    bars = ax.barh(y_pos, percentages, color=COLORS[algo], 
                                   edgecolor='black', linewidth=0.8, height=0.7)
                    
                    ax.set_yticks(y_pos)
                    ax.set_yticklabels(labels, fontsize=11)
                    ax.set_xlabel('Percentage (%)', fontsize=12)
                    ax.set_title(f'{ALGO_NAMES[algo]}', fontsize=14, fontweight='bold')
                    
                    # Scale x-axis appropriately
                    max_pct = max(percentages) if percentages else 10
                    x_limit = max(max_pct * 1.3, 5)
                    ax.set_xlim(0, x_limit)
                    ax.grid(axis='x', alpha=0.3)
                    
                    # Add percentage and count labels - color based on half of axis
                    half_axis = x_limit / 2
                    for bar, pct, cnt in zip(bars, percentages, counts):
                        width = bar.get_width()
                        # Black outside for bars shorter than half axis, white inside for longer
                        if width >= half_axis:
                            ax.text(width - 0.5, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='right', va='center',
                                   fontsize=10, fontweight='bold', color='white')
                        else:
                            ax.text(width + 0.3, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='left', va='center',
                                   fontsize=10, fontweight='bold', color='black')
        
        plt.suptitle(f'Most Common Sequence Endings - Last {n} Element{"s" if n > 1 else ""} (from 1)', 
                    fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(f'{OUTPUT_DIR}/plot4_endings_length_{n}.png', dpi=150, bbox_inches='tight')
        print(f"Saved: {OUTPUT_DIR}/plot4_endings_length_{n}.png")


def plot_common_beginnings_detailed(all_results):
    """Summary plot showing coverage trends across all algorithms."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 7))
    
    for idx, (algo, results) in enumerate(all_results.items()):
        ax = axes[idx]
        
        n_values = list(range(1, 7))  # Plot first 6
        top1_percentages = []
        top3_percentages = []
        top5_percentages = []
        
        for n in n_values:
            if n in results['beginning_counts']:
                data = results['beginning_counts'][n]
                if data['most_common']:
                    top1_pct = (data['most_common'][0][1] / data['total']) * 100
                    top3_pct = sum(c[1] for c in data['most_common'][:3]) / data['total'] * 100
                    top5_pct = sum(c[1] for c in data['most_common'][:5]) / data['total'] * 100
                    top1_percentages.append(top1_pct)
                    top3_percentages.append(top3_pct)
                    top5_percentages.append(top5_pct)
                else:
                    top1_percentages.append(0)
                    top3_percentages.append(0)
                    top5_percentages.append(0)
            else:
                top1_percentages.append(0)
                top3_percentages.append(0)
                top5_percentages.append(0)
        
        x = np.arange(len(n_values))
        width = 0.25
        
        bars1 = ax.bar(x - width, top1_percentages, width, label='Top 1', 
                      color=COLORS[algo], edgecolor='black', linewidth=1)
        bars3 = ax.bar(x, top3_percentages, width, label='Top 3', 
                      color=COLORS[algo], alpha=0.6, edgecolor='black', linewidth=1)
        bars5 = ax.bar(x + width, top5_percentages, width, label='Top 5', 
                      color=COLORS[algo], alpha=0.3, edgecolor='black', linewidth=1)
        
        ax.set_xlabel('Length of Ending (n elements from 1)', fontsize=12)
        ax.set_ylabel('Coverage (%)', fontsize=12)
        ax.set_title(f'{ALGO_NAMES[algo]}', fontsize=14, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels(n_values, fontsize=11)
        ax.legend(fontsize=10, loc='upper right')
        
        # Scale y-axis to data
        max_val = max(top5_percentages) if top5_percentages else 10
        ax.set_ylim(0, max(max_val * 1.2, 10))
        ax.grid(axis='y', alpha=0.3)
        
        # Add value labels on top 1 bars
        for bar, pct in zip(bars1, top1_percentages):
            if pct > 0:
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                       f'{pct:.1f}%', ha='center', va='bottom', fontsize=9, fontweight='bold')
    
    plt.suptitle('Coverage of Top Sequence Endings (from 1)', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/plot4_endings_coverage.png', dpi=150, bbox_inches='tight')
    print(f"Saved: {OUTPUT_DIR}/plot4_endings_coverage.png")


def export_to_txt(all_results):
    """Export analysis results to TXT files for each algorithm."""
    for algo, results in all_results.items():
        txt_path = f'{OUTPUT_DIR}/analysis_{algo}.txt'
        
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write(f"{'='*60}\n")
            f.write(f"  {ALGO_NAMES[algo]} - Analysis Results\n")
            f.write(f"{'='*60}\n\n")
            
            # Basic stats
            f.write(f"1. Number of sequences generated: {results['num_sequences']}\n")
            f.write(f"2. Average populations between sequences: {float(results['avg_interval']):.2f}\n\n")
            
            # Sequence statistics
            f.write(f"3. Sequence Statistics:\n")
            f.write(f"   Min sequence: {results['min_seq']}\n")
            f.write(f"   Avg sequence: {[round(float(x), 2) for x in results['avg_seq']]}\n")
            f.write(f"   Max sequence: {results['max_seq']}\n\n")
            
            f.write(f"   Position-by-position:\n")
            f.write(f"   {'Pos':<5} {'Min':<10} {'Avg':<12} {'Max':<10}\n")
            f.write(f"   {'-'*37}\n")
            for i in range(len(results['avg_seq'])):
                f.write(f"   {i+1:<5} {results['min_seq'][i]:<10} {results['avg_seq'][i]:<12.2f} {results['max_seq'][i]:<10}\n")
            
            # Sequence endings
            f.write(f"\n4. Sequence Endings (from 1):\n")
            for n, data in results['beginning_counts'].items():
                f.write(f"\n   Last {n} element(s) - {data['total']} sequences, {len(data['counts'])} unique patterns:\n")
                for seq, count in data['most_common']:
                    percentage = (count / data['total']) * 100
                    seq_str = ', '.join(map(str, seq))
                    f.write(f"      [{seq_str}]: {count} times ({percentage:.2f}%)\n")
        
        print(f"Saved: {txt_path}")


# Output directory
OUTPUT_DIR = 'outputs/SearchingAlgorithmsAnalysis'


def main():
    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    all_results = {}
    
    # Parse and analyze each file
    for algo, filename in FILES.items():
        filepath = os.path.join(RESULTS_DIR, filename)
        
        if not os.path.exists(filepath):
            print(f"Warning: File not found: {filepath}")
            continue
        
        print(f"Processing {ALGO_NAMES[algo]}...")
        sequences = parse_file(filepath)
        results = analyze_sequences(sequences)
        
        if results:
            all_results[algo] = results
            print_analysis(ALGO_NAMES[algo], results)
    
    if not all_results:
        print("No data to analyze!")
        return
    
    # Export to TXT
    print("\n" + "="*60)
    print("  EXPORTING TXT FILES")
    print("="*60)
    export_to_txt(all_results)
    
    # Generate plots
    print("\n" + "="*60)
    print("  GENERATING PLOTS")
    print("="*60)
    
    plot_num_sequences(all_results)
    plot_avg_interval(all_results)
    plot_common_beginnings(all_results)  # Now creates separate plots for each length
    plot_common_beginnings_detailed(all_results)
    
    print("\nAnalysis complete!")


if __name__ == "__main__":
    main()
